
# Default values

DEFAULT_PORT = 8265
DEFAULT_HEARTBEAT_TIMEOUT = 60
DEFAULT_SCHEDULING_INTERVAL = 5
DEFAULT_GPU_POLL_INTERVAL = 10
DEFAULT_GPU_UTIL_THRESHOLD = 10.0
DEFAULT_GPU_MEM_THRESHOLD = 10.0
DEFAULT_GPU_STABLE_TIME = 30
DEFAULT_JOB_STARTUP_GRACE = 120

# API

API_VERSION = "v1"
API_BASE_PATH = f"/api/{API_VERSION}"

# Paths

CONFIG_FILE_PATH = "~/.scheduler/config.yaml"
TEMP_DIR_PATH = "~/.scheduler/tmp"
LOG_DIR_PATH = "~/.scheduler/logs"

# Job polling

JOB_POLL_TIMEOUT = 30  # Long-polling timeout in seconds

# Exit codes

EXIT_SUCCESS = 0
EXIT_GENERAL_ERROR = 1
EXIT_ARGUMENT_ERROR = 2
EXIT_CONNECTION_ERROR = 3
EXIT_NOT_FOUND_ERROR = 4
EXIT_PERMISSION_ERROR = 5
EXIT_TIMEOUT_ERROR = 6
