from typing import List, Optional, Set, Dict
import logging
from datetime import datetime
import os

from scheduler.core import InvalidRequirementException, JobNotFoundException
from scheduler.core import Job, JobStatus, JobRequirement
from scheduler.core import Config
from scheduler.core import generate_job_id
from scheduler.manager.persistence import PersistenceManager

logger = logging.getLogger(__name__)


class JobManager:
    """Manages job queue and lifecycle"""

    def __init__(self, persistence: PersistenceManager, config: Config):
        """
        Initialize job manager.

        Args:
            persistence: PersistenceManager instance
            config: Configuration instance
        """
        self.persistence = persistence
        self.config = config
        self.jobs: Dict[str, Job] = {}

        # Load existing jobs from storage
        self._load_jobs()

    def _load_jobs(self):
        """Load jobs from storage into memory"""
        jobs = self.persistence.load_all_jobs()
        for job in jobs:
            self.jobs[job.job_id] = job
        logger.info(f"Loaded {len(jobs)} jobs from storage")

    def submit_job(
        self,
        script: str,
        requirements: str,
        name: Optional[str] = None,
        script_args: List[str] = None,
        working_dir: Optional[str] = None,
        env_vars: Dict[str, str] = None,
        dependencies: List[str] = None,
        priority: int = 0,
        job_id: Optional[str] = None,
        snapshot_ref: Optional[str] = None,
        snapshot_working_dir: Optional[str] = None,
    ) -> Job:
        """
        Submit a new job.

        Args:
            script: Path to script
            requirements: Requirement string
            name: Job name
            script_args: Script arguments
            working_dir: Working directory
            env_vars: Environment variables
            dependencies: Job dependencies
            priority: Job priority
            job_id: Pre-generated job ID (generated by client)
            snapshot_ref: Git snapshot reference (created by client)
            snapshot_working_dir: Workspace root where snapshot was created

        Returns:
            Created Job instance

        Raises:
            ValidationException: If parameters are invalid
        """
        # Parse requirements to validate
        job_requirements = JobRequirement(requirements)

        # Use pre-generated job_id from client, or generate one if not provided (backward compatibility)
        if job_id is None:
            job_id = generate_job_id()
            logger.debug(f"Generated job_id on head: {job_id}")
        else:
            logger.debug(f"Using client-provided job_id: {job_id}")

        job_name = name or os.path.basename(script)

        # working_dir should be set by the client, not the server
        # If not provided, we can't infer it correctly on the server side
        if working_dir is None:
            # Fallback to script directory if working_dir not provided
            # If script is just a filename, use current directory
            script_dir = os.path.dirname(os.path.abspath(script)) if script else None
            working_dir = script_dir if script_dir else os.getcwd()

        # Create job
        logger.info(f"[TRACE] Creating job {job_id} with env_vars: {env_vars}")
        job = Job(
            job_id=job_id,
            name=job_name,
            script=script,
            requirements=job_requirements,
            script_args=script_args,
            working_dir=working_dir,
            env_vars=env_vars,
            dependencies=dependencies,
            priority=priority,
            submitted_at=datetime.now(),
            status=JobStatus.PENDING,
            snapshot_ref=snapshot_ref,
            snapshot_working_dir=snapshot_working_dir,
        )
        logger.info(f"[TRACE] Job {job_id} created with env_vars: {job.env_vars}")

        if snapshot_ref:
            logger.info(f"Job {job_id} has snapshot {snapshot_ref} created by client at {snapshot_working_dir}")

        # Store in memory and persist
        self.jobs[job_id] = job
        self.persistence.save_job(job)

        logger.info(f"Job {job_id} ({job_name}) submitted")
        return job

    def get_job(self, job_id: str) -> Optional[Job]:
        """
        Get job by ID.

        Args:
            job_id: Job ID

        Returns:
            Job instance if found, None otherwise
        """
        return self.jobs.get(job_id)

    def list_jobs(
        self,
        status_filter: Optional[JobStatus] = None,
        limit: Optional[int] = None
    ) -> List[Job]:
        """
        List jobs with optional filtering.

        Args:
            status_filter: Filter by job status
            limit: Maximum number of jobs to return

        Returns:
            List of Job instances
        """
        jobs = list(self.jobs.values())

        # Apply status filter
        if status_filter is not None:
            jobs = [j for j in jobs if j.status == status_filter]

        # Sort by submission time (newest first)
        jobs.sort(key=lambda j: j.submitted_at, reverse=True)

        # Apply limit
        if limit is not None:
            jobs = jobs[:limit]

        return jobs

    def get_pending_jobs(self) -> List[Job]:
        """
        Get all pending jobs sorted by priority.

        Returns:
            List of pending Job instances
        """
        pending = [j for j in self.jobs.values() if j.status == JobStatus.PENDING]
        # Sort by priority (higher first), then by submission time (older first)
        pending.sort(key=lambda j: (-j.priority, j.submitted_at))
        return pending

    def get_running_jobs(self) -> List[Job]:
        """
        Get all running jobs.

        Returns:
            List of running Job instances
        """
        return [j for j in self.jobs.values() if j.status == JobStatus.RUNNING]

    def get_completed_job_ids(self) -> Set[str]:
        """
        Get set of completed job IDs.

        Returns:
            Set of job IDs that are completed
        """
        return {j.job_id for j in self.jobs.values() if j.status == JobStatus.COMPLETED}

    def start_job(self, job_id: str, node_name: str, gpu_ids: List[int]):
        """
        Mark job as started.

        Args:
            job_id: Job ID
            node_name: Node where job is starting
            gpu_ids: GPUs assigned to job

        Raises:
            JobNotFoundException: If job not found
        """
        job = self.jobs.get(job_id)
        if not job:
            raise JobNotFoundException(f"Job {job_id} not found")

        logger.info(f"[TRACE] Starting job {job_id} on node {node_name} with GPUs {gpu_ids}, env_vars: {job.env_vars}")
        job.status = JobStatus.RUNNING
        job.started_at = datetime.now()
        job.assigned_node = node_name
        job.assigned_gpus = gpu_ids

        self.persistence.save_job(job)
        logger.info(f"[TRACE] Job {job_id} marked as RUNNING on {node_name} with GPUs {gpu_ids}")

    def complete_job(self, job_id: str, exit_code: int):
        """
        Mark job as completed.

        Args:
            job_id: Job ID
            exit_code: Process exit code

        Raises:
            JobNotFoundException: If job not found
        """
        job = self.jobs.get(job_id)
        if not job:
            raise JobNotFoundException(f"Job {job_id} not found")

        job.status = JobStatus.COMPLETED
        job.completed_at = datetime.now()
        job.exit_code = exit_code

        self.persistence.save_job(job)
        logger.info(f"Job {job_id} completed with exit code {exit_code}")

    def fail_job(self, job_id: str, error_message: str):
        """
        Mark job as failed.

        Args:
            job_id: Job ID
            error_message: Error message

        Raises:
            JobNotFoundException: If job not found
        """
        job = self.jobs.get(job_id)
        if not job:
            raise JobNotFoundException(f"Job {job_id} not found")

        job.status = JobStatus.FAILED
        job.completed_at = datetime.now()
        job.error_message = error_message

        self.persistence.save_job(job)
        logger.error(f"Job {job_id} failed: {error_message}")

    def cancel_job(self, job_id: str):
        """
        Cancel a job.

        Args:
            job_id: Job ID

        Raises:
            JobNotFoundException: If job not found
        """
        job = self.jobs.get(job_id)
        if not job:
            raise JobNotFoundException(f"Job {job_id} not found")

        job.status = JobStatus.CANCELLED
        job.completed_at = datetime.now()

        self.persistence.save_job(job)
        logger.info(f"Job {job_id} cancelled")

    def purge_job(self, job_id: str):
        """
        Purge a specific job from the database immediately.
        Workers will clean up local files on their next heartbeat.

        Args:
            job_id: Job ID to purge

        Raises:
            JobNotFoundException: If job not found
        """
        job = self.jobs.get(job_id)
        if not job:
            raise JobNotFoundException(f"Job {job_id} not found")

        # Delete from storage immediately
        self.persistence.delete_job(job_id)
        del self.jobs[job_id]
        logger.info(f"Job {job_id} purged from database")

    def purge_jobs_by_criteria(
        self,
        before_time: Optional[datetime] = None,
        status_filter: Optional[List[str]] = None
    ) -> int:
        """
        Purge jobs from database based on time and status criteria.
        Jobs are immediately deleted from storage. Workers will clean up
        local files on their next heartbeat based on the active jobs list.

        Args:
            before_time: Purge jobs completed/failed/cancelled before this time
            status_filter: List of status values to purge (e.g., ['failed', 'completed', 'cancelled'])

        Returns:
            Number of jobs purged
        """
        if not status_filter:
            status_filter = ['failed', 'completed', 'cancelled']

        # Convert string status to JobStatus
        status_enums = []
        for status_str in status_filter:
            try:
                status_enums.append(JobStatus(status_str.lower()))
            except ValueError:
                logger.warning(f"Invalid status filter: {status_str}")

        purged_count = 0
        jobs_to_purge = []

        # Collect jobs to purge
        for job in self.jobs.values():
            # Check status
            if job.status not in status_enums:
                continue

            # Check time
            if before_time:
                if job.completed_at and job.completed_at < before_time:
                    jobs_to_purge.append(job.job_id)
                    logger.info(f"Purging job {job.job_id} (completed {job.completed_at})")
            else:
                # No time filter, purge all jobs matching status
                jobs_to_purge.append(job.job_id)
                logger.info(f"Purging job {job.job_id}")

        # Delete jobs from storage immediately
        for job_id in jobs_to_purge:
            self.persistence.delete_job(job_id)
            del self.jobs[job_id]
            purged_count += 1
            logger.info(f"Job {job_id} purged from database")

        return purged_count

    def get_active_jobs_for_node(self, node_name: str) -> List[str]:
        """
        Get list of active job IDs for a specific node.
        Workers use this list to know which jobs to keep - any jobs
        not in this list should be cleaned up locally.

        Args:
            node_name: Node name

        Returns:
            List of job IDs that are currently active on this node
        """
        active_jobs = []
        for job in self.jobs.values():
            # Only include jobs assigned to this node
            if job.assigned_node == node_name:
                active_jobs.append(job.job_id)
        return active_jobs
