from typing import List, Optional, Set, Dict
import logging
from datetime import datetime
import os
import asyncio

from scheduler.core import InvalidRequirementException, JobNotFoundException
from scheduler.core import Job, JobStatus, JobRequirement
from scheduler.core import Config
from scheduler.core import generate_job_id
from scheduler.core import parse_tqdm_eta
from scheduler.manager.persistence import PersistenceManager

logger = logging.getLogger(__name__)


class JobManager:
    """Manages job queue and lifecycle"""
    
    # Class attributes with type hints and defaults for spec_set compatibility
    jobs: Dict[str, Job] = {}
    persistence: PersistenceManager = None
    config: Config = None

    def __init__(self, persistence: PersistenceManager, config: Config):
        """
        Initialize job manager.

        Args:
            persistence: PersistenceManager instance
            config: Configuration instance
        """
        self.persistence = persistence
        self.config = config
        self.jobs: Dict[str, Job] = {}

        # Event system for long-polling
        # Maps node_name -> asyncio.Event that gets set when a new job is assigned
        self._job_assignment_events: Dict[str, asyncio.Event] = {}

        # Load existing jobs from storage
        self._load_jobs()

    def _load_jobs(self):
        """Load jobs from storage into memory"""
        jobs = self.persistence.load_all_jobs()
        for job in jobs:
            self.jobs[job.job_id] = job
        logger.info(f"Loaded {len(jobs)} jobs from storage")

    def get_job_assignment_event(self, node_name: str) -> asyncio.Event:
        """
        Get or create an event for job assignments to a specific node.

        Args:
            node_name: Node name

        Returns:
            Event that gets set when a new job is assigned to this node
        """
        if node_name not in self._job_assignment_events:
            self._job_assignment_events[node_name] = asyncio.Event()
        return self._job_assignment_events[node_name]

    def resolve_dependency_shorthand(self, dependency: str) -> str:
        """
        Resolve ^ shorthand syntax to actual job ID.

        Args:
            dependency: Either a job ID or ^ syntax (^, ^^, ^^^, etc.)

        Returns:
            Resolved job ID

        Raises:
            ValueError: If invalid syntax or insufficient history
        """
        # If doesn't start with ^, return as-is (already a job ID)
        if not dependency.startswith('^'):
            return dependency

        # Count the number of carets to determine how far back
        caret_count = len(dependency)
        if not all(c == '^' for c in dependency):
            # Invalid syntax like "^a" or "a^"
            raise ValueError(f"Invalid dependency syntax: '{dependency}'. Use only ^ characters (e.g., ^, ^^, ^^^)")

        # Get recent jobs, excluding FAILED and CANCELLED
        exclude_states = {JobStatus.FAILED, JobStatus.CANCELLED}
        recent_jobs = [
            job for job in self.jobs.values()
            if job.status not in exclude_states
        ]

        # Sort by submission time (newest first)
        recent_jobs.sort(key=lambda j: j.submitted_at, reverse=True)

        # Check if we have enough job history
        if len(recent_jobs) == 0:
            raise ValueError("No previous jobs to reference with '^'")

        # Index is caret_count - 1 (^ = 0, ^^ = 1, etc.)
        index = caret_count - 1

        if index >= len(recent_jobs):
            raise ValueError(
                f"Only {len(recent_jobs)} job{'s' if len(recent_jobs) != 1 else ''} available, "
                f"cannot resolve '{dependency}' ({caret_count} job{'s' if caret_count != 1 else ''} back)"
            )

        resolved_job_id = recent_jobs[index].job_id
        return resolved_job_id

    def submit_job(
        self,
        script: str,
        requirements: str,
        name: Optional[str] = None,
        script_args: List[str] = None,
        working_dir: Optional[str] = None,
        env_vars: Dict[str, str] = None,
        dependencies: List[str] = None,
        priority: int = 0,
        job_id: Optional[str] = None,
        snapshot_ref: Optional[str] = None,
        snapshot_working_dir: Optional[str] = None,
    ) -> Job:
        """
        Submit a new job.

        Args:
            script: Path to script
            requirements: Requirement string
            name: Job name
            script_args: Script arguments
            working_dir: Working directory
            env_vars: Environment variables
            dependencies: Job dependencies
            priority: Job priority
            job_id: Pre-generated job ID (generated by client)
            snapshot_ref: Git snapshot reference (created by client)
            snapshot_working_dir: Workspace root where snapshot was created

        Returns:
            Created Job instance

        Raises:
            ValidationException: If parameters are invalid
        """
        # Parse requirements to validate
        job_requirements = JobRequirement(requirements)

        # Use pre-generated job_id from client, or generate one if not provided (backward compatibility)
        if job_id is None:
            job_id = generate_job_id()
            logger.debug(f"Generated job_id on head: {job_id}")
        else:
            logger.debug(f"Using client-provided job_id: {job_id}")

        job_name = name or os.path.basename(script)

        # working_dir should be set by the client, not the server
        # If not provided, we can't infer it correctly on the server side
        if working_dir is None:
            # Fallback to script directory if working_dir not provided
            # If script is just a filename, use current directory
            script_dir = os.path.dirname(os.path.abspath(script)) if script else None
            working_dir = script_dir if script_dir else os.getcwd()

        # Resolve ^ syntax in dependencies
        resolved_dependencies = []
        if dependencies:
            for dep in dependencies:
                resolved_dep = self.resolve_dependency_shorthand(dep)
                resolved_dependencies.append(resolved_dep)
                if resolved_dep != dep:
                    logger.info(f"Resolved dependency '{dep}' -> {resolved_dep}")

        # Create job
        job = Job(
            job_id=job_id,
            name=job_name,
            script=script,
            requirements=job_requirements,
            script_args=script_args,
            working_dir=working_dir,
            env_vars=env_vars,
            dependencies=resolved_dependencies if resolved_dependencies else None,
            priority=priority,
            submitted_at=datetime.now(),
            status=JobStatus.PENDING,
            snapshot_ref=snapshot_ref,
            snapshot_working_dir=snapshot_working_dir,
        )

        if snapshot_ref:
            logger.info(f"Job {job_id} has snapshot {snapshot_ref} created by client at {snapshot_working_dir}")

        # Store in memory and persist
        self.jobs[job_id] = job
        self.persistence.save_job(job)

        logger.info(f"Job {job_id} ({job_name}) submitted")
        return job

    def get_job(self, job_id: str) -> Optional[Job]:
        """
        Get job by ID.

        Args:
            job_id: Job ID

        Returns:
            Job instance if found, None otherwise
        """
        job = self.jobs.get(job_id)
        if job:
            self._enrich_job_with_eta(job)
        return job

    def _enrich_job_with_eta(self, job: Job):
        """
        Enrich a job with ETA parsed from stderr logs.

        Args:
            job: Job to enrich with ETA
        """
        # Only parse ETA for running jobs
        if job.status != JobStatus.RUNNING:
            job.eta = None
            return

        # Read stderr log
        log_dir = os.path.expanduser(self.config.worker.log_dir)
        stderr_path = os.path.join(log_dir, f"{job.job_id}.stderr.log")

        if not os.path.exists(stderr_path):
            job.eta = None
            return

        try:
            # Read last few lines of stderr (tqdm usually outputs to the last line)
            with open(stderr_path, 'r') as f:
                # Seek to end and read last N bytes to get last few lines
                # This is more efficient than reading the entire file
                file_size = os.path.getsize(stderr_path)
                # Read last 2KB which should be enough for tqdm output
                read_size = min(2048, file_size)
                f.seek(max(0, file_size - read_size))
                stderr_tail = f.read()

            # Parse ETA from stderr
            eta = parse_tqdm_eta(stderr_tail)
            job.eta = eta
        except Exception as e:
            logger.debug(f"Failed to parse ETA for job {job.job_id}: {e}")
            job.eta = None

    def list_jobs(
        self,
        status_filter: Optional[JobStatus] = None,
        limit: Optional[int] = None
    ) -> List[Job]:
        """
        List jobs with optional filtering.

        Args:
            status_filter: Filter by job status
            limit: Maximum number of jobs to return

        Returns:
            List of Job instances
        """
        jobs = list(self.jobs.values())

        # Apply status filter
        if status_filter is not None:
            jobs = [j for j in jobs if j.status == status_filter]

        # Sort by submission time (newest first)
        jobs.sort(key=lambda j: j.submitted_at, reverse=True)

        # Apply limit
        if limit is not None:
            jobs = jobs[:limit]

        # Enrich jobs with ETA
        for job in jobs:
            self._enrich_job_with_eta(job)

        return jobs

    def get_pending_jobs(self) -> List[Job]:
        """
        Get all pending jobs sorted by priority.

        Returns:
            List of pending Job instances
        """
        pending = [j for j in self.jobs.values() if j.status == JobStatus.PENDING]
        # Sort by priority (higher first), then by submission time (older first)
        pending.sort(key=lambda j: (-j.priority, j.submitted_at))
        return pending

    def get_running_jobs(self) -> List[Job]:
        """
        Get all running jobs.

        Returns:
            List of running Job instances
        """
        return [j for j in self.jobs.values() if j.status == JobStatus.RUNNING]

    def get_completed_job_ids(self) -> Set[str]:
        """
        Get set of completed job IDs.

        Returns:
            Set of job IDs that are completed
        """
        return {j.job_id for j in self.jobs.values() if j.status == JobStatus.COMPLETED}

    def start_job(self, job_id: str, node_name: str, gpu_ids: List[int]):
        """
        Mark job as started.

        Args:
            job_id: Job ID
            node_name: Node where job is starting
            gpu_ids: GPUs assigned to job

        Raises:
            JobNotFoundException: If job not found
        """
        job = self.jobs.get(job_id)
        if not job:
            raise JobNotFoundException(f"Job {job_id} not found")

        job.status = JobStatus.RUNNING
        job.started_at = datetime.now()
        job.assigned_node = node_name
        job.assigned_gpus = gpu_ids

        self.persistence.save_job(job)
        logger.info(f"Job {job_id} started on {node_name} with GPUs {gpu_ids}")

        # Notify any workers polling for this node (create event if needed)
        event = self.get_job_assignment_event(node_name)
        event.set()

    def complete_job(self, job_id: str, exit_code: int, after_commit_ref: Optional[str] = None):
        """
        Mark job as completed.

        Args:
            job_id: Job ID
            exit_code: Process exit code
            after_commit_ref: Optional commit SHA of the "after" commit

        Raises:
            JobNotFoundException: If job not found
        """
        job = self.jobs.get(job_id)
        if not job:
            raise JobNotFoundException(f"Job {job_id} not found")

        job.status = JobStatus.COMPLETED
        job.completed_at = datetime.now()
        job.exit_code = exit_code
        if after_commit_ref:
            job.after_commit_ref = after_commit_ref

        self.persistence.save_job(job)
        logger.info(f"Job {job_id} completed with exit code {exit_code}")

    def fail_job(self, job_id: str, error_message: str, after_commit_ref: Optional[str] = None):
        """
        Mark job as failed.

        Args:
            job_id: Job ID
            error_message: Error message
            after_commit_ref: Optional commit SHA of the "after" commit

        Raises:
            JobNotFoundException: If job not found
        """
        job = self.jobs.get(job_id)
        if not job:
            raise JobNotFoundException(f"Job {job_id} not found")

        job.status = JobStatus.FAILED
        job.completed_at = datetime.now()
        job.error_message = error_message
        if after_commit_ref:
            job.after_commit_ref = after_commit_ref

        self.persistence.save_job(job)
        logger.error(f"Job {job_id} failed: {error_message}")

    def cancel_job(self, job_id: str):
        """
        Cancel a job.

        Args:
            job_id: Job ID

        Raises:
            JobNotFoundException: If job not found
        """
        job = self.jobs.get(job_id)
        if not job:
            raise JobNotFoundException(f"Job {job_id} not found")

        job.status = JobStatus.CANCELLED
        job.completed_at = datetime.now()

        self.persistence.save_job(job)
        logger.info(f"Job {job_id} cancelled")

    def untrack_job(self, job_id: str):
        """
        Mark a job as untracked (scheduler stopped while job was running).

        Args:
            job_id: Job ID

        Raises:
            JobNotFoundException: If job not found
        """
        job = self.jobs.get(job_id)
        if not job:
            raise JobNotFoundException(f"Job {job_id} not found")

        job.status = JobStatus.UNTRACKED
        # Don't set completed_at since the job is still running, just untracked

        self.persistence.save_job(job)
        logger.info(f"Job {job_id} marked as untracked")

    def retry_job_inplace(self, job_id: str) -> Job:
        """
        Retry a job in-place by reverting it to PENDING state.

        This resets the job to PENDING and clears execution-related fields,
        while keeping the original snapshot_ref, dependencies, and submission fields.
        The job will be re-executed in the original branch with the "before" commit.

        Args:
            job_id: Job ID to retry

        Returns:
            The updated job

        Raises:
            JobNotFoundException: If job not found
            ValueError: If job is not in a terminal state (FAILED, CANCELLED, COMPLETED)
        """
        job = self.jobs.get(job_id)
        if not job:
            raise JobNotFoundException(f"Job {job_id} not found")

        # Validate job is in terminal state
        if job.status not in [JobStatus.FAILED, JobStatus.CANCELLED, JobStatus.COMPLETED]:
            raise ValueError(f"Job {job_id} is in {job.status.value} state. "
                           f"Can only retry FAILED, CANCELLED, or COMPLETED jobs.")

        # Reset to PENDING state
        job.status = JobStatus.PENDING

        # Clear execution-related fields
        job.started_at = None
        job.completed_at = None
        job.exit_code = None
        job.error_message = None
        job.assigned_node = None
        job.assigned_gpus = []
        job.after_commit_ref = None  # Will be recreated on next execution

        # Keep unchanged:
        # - job_id (same job)
        # - snapshot_ref (before commit - unchanged)
        # - snapshot_working_dir (unchanged)
        # - dependencies (already resolved - unchanged)
        # - name, script, requirements, script_args, env_vars, working_dir, priority, submitted_at

        self.persistence.save_job(job)
        logger.info(f"Job {job_id} retried in-place (reset to PENDING)")

        return job

    def purge_job(self, job_id: str):
        """
        Purge a specific job from the database immediately.
        Workers will clean up local files on their next heartbeat.

        Args:
            job_id: Job ID to purge

        Raises:
            JobNotFoundException: If job not found
        """
        job = self.jobs.get(job_id)
        if not job:
            raise JobNotFoundException(f"Job {job_id} not found")

        # Delete from storage immediately
        self.persistence.delete_job(job_id)
        del self.jobs[job_id]
        logger.info(f"Job {job_id} purged from database")

    def purge_jobs_by_criteria(
        self,
        before_time: Optional[datetime] = None,
        status_filter: Optional[List[str]] = None
    ) -> int:
        """
        Purge jobs from database based on time and status criteria.
        Jobs are immediately deleted from storage. Workers will clean up
        local files on their next heartbeat based on the active jobs list.

        Args:
            before_time: Purge jobs completed/failed/cancelled before this time
            status_filter: List of status values to purge (e.g., ['failed', 'completed', 'cancelled'])

        Returns:
            Number of jobs purged
        """
        if not status_filter:
            status_filter = ['failed', 'completed', 'cancelled']

        # Convert string status to JobStatus
        status_enums = []
        for status_str in status_filter:
            try:
                status_enums.append(JobStatus(status_str.lower()))
            except ValueError:
                logger.warning(f"Invalid status filter: {status_str}")

        purged_count = 0
        jobs_to_purge = []

        # Collect jobs to purge
        for job in self.jobs.values():
            # Check status
            if job.status not in status_enums:
                continue

            # Check time
            if before_time:
                if job.completed_at and job.completed_at < before_time:
                    jobs_to_purge.append(job.job_id)
                    logger.info(f"Purging job {job.job_id} (completed {job.completed_at})")
            else:
                # No time filter, purge all jobs matching status
                jobs_to_purge.append(job.job_id)
                logger.info(f"Purging job {job.job_id}")

        # Delete jobs from storage immediately
        for job_id in jobs_to_purge:
            self.persistence.delete_job(job_id)
            del self.jobs[job_id]
            purged_count += 1
            logger.info(f"Job {job_id} purged from database")

        return purged_count

    def get_active_jobs_for_node(self, node_name: str) -> List[str]:
        """
        Get list of active job IDs for a specific node.
        Workers use this list to know which jobs to keep - any jobs
        not in this list should be cleaned up locally.

        Args:
            node_name: Node name

        Returns:
            List of job IDs that are currently active on this node
        """
        active_jobs = []
        for job in self.jobs.values():
            # Only include jobs assigned to this node
            if job.assigned_node == node_name:
                active_jobs.append(job.job_id)
        return active_jobs
